name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies for LeetCode.Solutions
      run: dotnet restore LeetCode.Solutions/LeetCode.Solutions.csproj
      
    - name: Build LeetCode.Solutions
      run: dotnet build LeetCode.Solutions/LeetCode.Solutions.csproj --configuration Release
      
    - name: Test LeetCode.Solutions
      run: dotnet test LeetCode.Tests/LeetCode.Tests.csproj --configuration Release --no-build --verbosity normal
